### PR TITLE
Update caw.vim

### PR DESCRIPTION
**Pull request by DCMMC**
To add box comment for python.

### CODE REVIEW

**Comment by tyru** [comment]
Python does not have wrap comment / box comment (like C `/*` - `*/`).
If you want to add own comments (or docstring as box comment? :), you can define buffer-local variables when:

* `FileType`
  * `autocmd FileType python let b:caw_wrap_oneline_comment = ['#', '#']`
* Or, add file `~/.vim/after/ftplugin/python.vim` and define variables like: `let b:caw_wrap_oneline_comment = ['#', '#']`

**Comment by tyru** [comment]
closable?

**Comment by DCMMC** [comment]
right, you can close it.

**Comment by tyru** [comment]
Thanks.

**Comment by brandonpittman** [comment]
Just curious. Which languages support *box* comments?

**Comment by tyru** [comment]
Here is the supported languages.
https://github.com/tyru/caw.vim/blob/e82ae00f3fc03289d4054b44f100025a1bc81939/macros/generate-ftplugins.vim#L398-L407

* arduino
* c
* cpp
* perl
* ruby
* swig

**Comment by brandonpittman** [comment]
Thank you very much!

**Pull request closed without merging**
